version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_BASE_URL=https://sezginyurdakul.com/catering_api
    container_name: catering_frontend_prod
    restart: unless-stopped
    ports:
      - "8082:80"
    networks:
      - catering-network

networks:
  catering-network:
    name: catering-api_catering_network
    external: true
